/**
 * "Aperiodic Sets" family: the two golden rhombohedra, the 3D Penrose
 * pair (the Ammann–Kramer tiling of the icosahedral quasicrystal).
 * Each fills space on its own, periodically (any rhombohedron does), so
 * they are not a Space-Filling Pair; what is special is that together
 * they can also fill space with no repeat at all. (Face-to-face attaching
 * alone doesn't force that: in 3D it takes extra matching rules, or the
 * cut-and-project construction Rhombiverse's 6D world uses.)
 *
 * Built from three of the icosahedron's six 5-fold axes, each scaled to
 * the edge of this registry's RHOMBIC_TRIACONTAHEDRON (catalan.ts, edge
 * 1/phi at circumradius 1) -- not rescaled per shape, so their golden
 * rhombus faces are literally the triacontahedron's own and
 * facesCongruent() lets them attach to it and to each other (see
 * rd-relatives/index.ts for why a per-shape rescale would break that).
 *   prolate: axes pairwise at +1/sqrt5 (apex angles 63.435 deg)
 *   oblate:  axes pairwise at -1/sqrt5 (apex angles 116.565 deg)
 * Volumes are in the golden ratio. Each face lists its ACUTE corner
 * first, wound outward (the vertex-0 role computeFaceAttach relies on).
 * Generated by the same construction as Rhombiverse's
 * quasicrystal.js golden rhombohedra; checked in
 * scripts/verify-aperiodic-sets.ts.
 *
 * Known builds (assemblyNaming.ts): 2 prolate + 2 oblate = the Bilinski
 * dodecahedron, 5 + 5 = the rhombic icosahedron, 10 + 10 = the rhombic
 * triacontahedron.
 */

import { type Vec3, type PolyhedronSpec, buildConnectors } from './core';
import { centred, edgesOf, outward } from './convexBuild';

const VERTS_GOLDEN_PROLATE: Vec3[] = [
  [-0.2628655560595668, 0.0, -0.6881909602355867],
  [-0.2628655560595668, 0.3249196962329063, -0.1624598481164531],
  [-0.2628655560595668, -0.3249196962329063, -0.1624598481164531],
  [-0.2628655560595668, 0.0, 0.3632712640026805],
  [0.2628655560595668, 0.0, -0.3632712640026804],
  [0.2628655560595668, 0.3249196962329063, 0.1624598481164532],
  [0.2628655560595668, -0.3249196962329063, 0.1624598481164532],
  [0.2628655560595668, 0.0, 0.6881909602355867],
];
const EDGES_GOLDEN_PROLATE: [number, number][] = [
  [0, 1], [0, 2], [0, 4], [1, 3], [1, 5], [2, 3], [2, 6], [3, 7], [4, 5], [4, 6], [5, 7], [6, 7],
];
const FACES_GOLDEN_PROLATE: number[][] = [
  [0, 2, 3, 1], [4, 5, 7, 6], [0, 1, 5, 4], [2, 6, 7, 3], [0, 4, 6, 2], [1, 3, 7, 5],
];

const VERTS_GOLDEN_OBLATE: Vec3[] = [
  [-0.10040570794311365, 0.10040570794311365, -0.10040570794311365],
  [-0.10040570794311365, 0.42532540417601994, 0.42532540417601994],
  [0.42532540417601994, 0.10040570794311365, -0.42532540417601994],
  [0.42532540417601994, 0.42532540417601994, 0.10040570794311365],
  [-0.42532540417601994, -0.42532540417601994, -0.10040570794311365],
  [-0.42532540417601994, -0.10040570794311365, 0.42532540417601994],
  [0.10040570794311365, -0.42532540417601994, -0.42532540417601994],
  [0.10040570794311365, -0.10040570794311365, 0.10040570794311365],
];
const EDGES_GOLDEN_OBLATE: [number, number][] = [
  [0, 1], [0, 2], [0, 4], [1, 3], [1, 5], [2, 3], [2, 6], [3, 7], [4, 5], [4, 6], [5, 7], [6, 7],
];
const FACES_GOLDEN_OBLATE: number[][] = [
  [1, 3, 2, 0], [6, 7, 5, 4], [4, 5, 1, 0], [3, 7, 6, 2], [2, 6, 4, 0], [5, 7, 3, 1],
];

// The Penrose rhombus prisms (direct decisions 2026-09-30): the thick
// (72°) and thin (36°) Penrose rhombi, edge 1, raised into prisms one edge
// tall (as in Rhombiverse's 5D world, PRISM_HEIGHT = 1), so their sides
// are unit squares that attach to the cube. Each fills space alone; the
// pair tiles every layer the Penrose way, never repeating across the
// layer, though the layers repeat straight up (the 5D decagonal
// quasicrystal). The golden rhombohedra never repeat in any direction.
function penrosePrism(angleDeg: number): { vertices: Vec3[]; edges: [number, number][]; faces: number[][] } {
  const t = (angleDeg * Math.PI) / 180;
  const base: [number, number][] = [[0, 0], [1, 0], [1 + Math.cos(t), Math.sin(t)], [Math.cos(t), Math.sin(t)]];
  const vertices = centred([...base.map(([x, z]): Vec3 => [x, -0.5, z]), ...base.map(([x, z]): Vec3 => [x, 0.5, z])]);
  const faces = outward(vertices, [[0, 1, 2, 3], [4, 5, 6, 7], [0, 1, 5, 4], [1, 2, 6, 5], [2, 3, 7, 6], [3, 0, 4, 7]]);
  return { vertices, edges: edgesOf(faces), faces };
}
const THICK = penrosePrism(72);
const THIN = penrosePrism(36);
const prismSpec = (id: string, name: string, g: typeof THICK): PolyhedronSpec => ({
  id,
  name,
  faceCount: g.faces.length,
  vertices: g.vertices,
  edges: g.edges,
  faces: g.faces,
  connectors: buildConnectors(g.vertices, g.edges),
  attachableFaceIndices: g.faces.map((_, i) => i),
});

export const APERIODIC_ADDITIONS: Record<string, PolyhedronSpec> = {
  GOLDEN_RHOMBOHEDRON_PROLATE: {
    id: 'GOLDEN_RHOMBOHEDRON_PROLATE',
    name: 'prolate golden rhombohedron',
    faceCount: FACES_GOLDEN_PROLATE.length,
    vertices: VERTS_GOLDEN_PROLATE,
    edges: EDGES_GOLDEN_PROLATE,
    faces: FACES_GOLDEN_PROLATE,
    connectors: buildConnectors(VERTS_GOLDEN_PROLATE, EDGES_GOLDEN_PROLATE),
    attachableFaceIndices: FACES_GOLDEN_PROLATE.map((_, i) => i),
  },
  GOLDEN_RHOMBOHEDRON_OBLATE: {
    id: 'GOLDEN_RHOMBOHEDRON_OBLATE',
    name: 'oblate golden rhombohedron',
    faceCount: FACES_GOLDEN_OBLATE.length,
    vertices: VERTS_GOLDEN_OBLATE,
    edges: EDGES_GOLDEN_OBLATE,
    faces: FACES_GOLDEN_OBLATE,
    connectors: buildConnectors(VERTS_GOLDEN_OBLATE, EDGES_GOLDEN_OBLATE),
    attachableFaceIndices: FACES_GOLDEN_OBLATE.map((_, i) => i),
  },
};
APERIODIC_ADDITIONS.PENROSE_PRISM_THICK = prismSpec('PENROSE_PRISM_THICK', 'thick Penrose rhombus prism', THICK);
APERIODIC_ADDITIONS.PENROSE_PRISM_THIN = prismSpec('PENROSE_PRISM_THIN', 'thin Penrose rhombus prism', THIN);
export const APERIODIC_ADDITION_IDS = Object.keys(APERIODIC_ADDITIONS);
/** The family holds two separate pairs, each a set of partners. */
export const APERIODIC_PAIRS: [string, string][] = [
  ['GOLDEN_RHOMBOHEDRON_PROLATE', 'GOLDEN_RHOMBOHEDRON_OBLATE'],
  ['PENROSE_PRISM_THICK', 'PENROSE_PRISM_THIN'],
];
