/**
 * Composite-Seed RCP investigation, Stage 6 — Question B ("What
 * geometric structure, if any, is generated by the complete RD-derived
 * mirror system?", hypothesis.md §11-§12).
 *
 * A DELIBERATE, DOCUMENTED INTERPRETIVE CHOICE (see
 * docs/composite-seed-rcp/reflectionGroup.md for the full reasoning):
 * hypothesis.md §12 Step 1-2 literally describe lifting a SPECIFIC
 * aggregate's own exposed facets into 4D via the RCP map -- but that
 * lift needs a theta (embedding-depth angle) the way each of the 4
 * ALREADY-VERIFIED regular seeds has one (tetrahedron/cube/octahedron/
 * dodecahedron, radialProjection.ts's own FOUR_D_SHAPE_PARAMS), and a
 * composite aggregate has no such theta -- inventing one here would be
 * exactly the kind of "silently re-derived from memory" the
 * investigation plan's own verification caveat warns against.
 *
 * This file instead answers the MORE FAITHFUL reading of hypothesis.md
 * §11's own question ("the complete RD-derived mirror system", stated
 * as an intrinsic property of the RD cell, not of any one aggregate):
 * the RD's own 12 facet-normal directions (Delta_RD), used as mirror
 * PLANES through the origin in 3D. This sidesteps the open-ended
 * "orbit growth to unknown depth" problem the investigation plan's own
 * Stage 6 acceptance criterion warns about: any group generated by a
 * FINITE set of reflections through the origin in R^3 with RATIONAL
 * (here: <110>-type) normals is a subgroup of a KNOWN finite point
 * group (order <= 48, the full octahedral group O_h) -- it is
 * mathematically guaranteed to close after boundedly many steps, not
 * an open question of "how deep is deep enough."
 */

import type { Vec3 } from '../core';
import { DELTA_RD } from './lattice';

export type Mat3 = [[number, number, number], [number, number, number], [number, number, number]];

function normalize(v: Vec3): Vec3 {
  const n = Math.hypot(v[0], v[1], v[2]);
  return [v[0] / n, v[1] / n, v[2] / n];
}

/** I - 2mm^T for a unit normal m -- the standard 3D reflection matrix, same convention as radialProjection.ts's own reflectionMatrix (just one dimension down). */
export function reflectionMatrix3(m: Vec3): Mat3 {
  const r: number[][] = [[0, 0, 0], [0, 0, 0], [0, 0, 0]];
  for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) r[i][j] = (i === j ? 1 : 0) - 2 * m[i] * m[j];
  return r as Mat3;
}

export function matMul3(a: Mat3, b: Mat3): Mat3 {
  const r: number[][] = [[0, 0, 0], [0, 0, 0], [0, 0, 0]];
  for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) {
    let s = 0;
    for (let k = 0; k < 3; k++) s += a[i][k] * b[k][j];
    r[i][j] = s;
  }
  return r as Mat3;
}

export function matVec3(a: Mat3, v: Vec3): Vec3 {
  return [0, 1, 2].map((i) => a[i][0] * v[0] + a[i][1] * v[1] + a[i][2] * v[2]) as Vec3;
}

const IDENTITY3: Mat3 = [[1, 0, 0], [0, 1, 0], [0, 0, 1]];

function matKey(m: Mat3): string {
  return m.flat().map((c) => Math.round(c * 1e6) / 1e6).join(',');
}

/**
 * Deduplicated distinct mirror PLANES from DELTA_RD's 12 directions --
 * v and -v define the SAME reflection matrix (I-2mm^T is identical for
 * m and -m, since the outer product mm^T doesn't change sign), so 12
 * directions collapse to exactly 6 distinct generators. Checked, not
 * assumed: reflectionMatrix3(v) and reflectionMatrix3(-v) are compared
 * directly in the verify script.
 */
export function distinctRdMirrorNormals(): Vec3[] {
  const seen = new Set<string>();
  const result: Vec3[] = [];
  for (const d of DELTA_RD) {
    const n = normalize(d);
    const canonical = n[0] > 0 || (n[0] === 0 && (n[1] > 0 || (n[1] === 0 && n[2] > 0))) ? n : ([-n[0], -n[1], -n[2]] as Vec3);
    const key = canonical.map((c) => Math.round(c * 1e6) / 1e6).join(',');
    if (!seen.has(key)) {
      seen.add(key);
      result.push(canonical);
    }
  }
  return result;
}

/**
 * Step 1+2 (this file's own interpretation, see header): the generating
 * reflection matrices themselves -- one per distinct RD mirror normal.
 */
export function rdGeneratingReflections(): Mat3[] {
  return distinctRdMirrorNormals().map(reflectionMatrix3);
}

/**
 * Step 6 analogue + closure: BFS group closure starting from the
 * identity, repeatedly multiplying every known element by every
 * generator, until no new element appears. GUARANTEED to terminate
 * (see file header) -- capped at `maxOrder` purely as a defensive
 * sanity bound (a bug producing an actually-infinite result would hit
 * this and should be reported as a bug, not silently truncated as
 * "finite").
 */
export interface GroupClosureResult {
  order: number;
  elements: Mat3[];
  /** True iff closure completed before hitting maxOrder -- false would mean either a real infinite group (shouldn't happen per the file header's own guarantee) or a bug. */
  closed: boolean;
}

export function closeGroup(generators: Mat3[], maxOrder = 200): GroupClosureResult {
  const seen = new Map<string, Mat3>([[matKey(IDENTITY3), IDENTITY3]]);
  const queue: Mat3[] = [IDENTITY3];
  while (queue.length > 0) {
    const g = queue.shift()!;
    for (const gen of generators) {
      const product = matMul3(gen, g);
      const key = matKey(product);
      if (!seen.has(key)) {
        if (seen.size >= maxOrder) return { order: seen.size, elements: [...seen.values()], closed: false };
        seen.set(key, product);
        queue.push(product);
      }
    }
  }
  return { order: seen.size, elements: [...seen.values()], closed: true };
}

/**
 * Step 7 analogue: orbit of a GENERIC point (no special symmetry of its
 * own -- irrational-ish coordinates chosen so it isn't accidentally
 * fixed by any nontrivial group element) under the closed group. For a
 * genuinely generic point, orbit size == group order (trivial
 * stabilizer) -- checked directly rather than assumed, since a
 * non-generic point could have a smaller orbit.
 */
export function orbitOfPoint(elements: Mat3[], p: Vec3): Vec3[] {
  const seen = new Map<string, Vec3>();
  for (const g of elements) {
    const q = matVec3(g, p);
    const key = q.map((c) => Math.round(c * 1e6) / 1e6).join(',');
    if (!seen.has(key)) seen.set(key, q);
  }
  return [...seen.values()];
}

// ---------------------------------------------------------------------
// Steps 3-6: pairwise angles, Coxeter compatibility, Gram matrix,
// positive-definiteness/rank.
// ---------------------------------------------------------------------

export interface PairwiseAngle {
  i: number;
  j: number;
  cosAlpha: number;
  alphaDeg: number;
  /** pi/alpha rounded, if within tolerance of an integer -- the Coxeter m_ij candidate. */
  m?: number;
}

function dot3(a: Vec3, b: Vec3): number {
  return a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
}

export function pairwiseAngles(normals: Vec3[]): PairwiseAngle[] {
  const TOL = 1e-6;
  const results: PairwiseAngle[] = [];
  for (let i = 0; i < normals.length; i++) {
    for (let j = i + 1; j < normals.length; j++) {
      const cosAlpha = Math.min(1, Math.max(-1, Math.abs(dot3(normals[i], normals[j]))));
      const alphaRad = Math.acos(cosAlpha);
      const alphaDeg = (alphaRad * 180) / Math.PI;
      let m: number | undefined;
      if (alphaRad > 1e-9) {
        const piOverAlpha = Math.PI / alphaRad;
        const rounded = Math.round(piOverAlpha);
        if (Math.abs(piOverAlpha - rounded) < TOL) m = rounded;
      }
      results.push({ i, j, cosAlpha, alphaDeg, m });
    }
  }
  return results;
}

/** G_ij = -cos(pi/m_ij) for Coxeter-compatible pairs (1 on the diagonal), else the DIRECTLY MEASURED -cos(alpha_ij) -- hypothesis.md §12 Step 5's own instruction to produce both the idealized and the measured matrix; here unified into one matrix that prefers the idealized value only where compatibility was actually confirmed. */
export function gramMatrix(normals: Vec3[], angles: PairwiseAngle[]): number[][] {
  const n = normals.length;
  const G: number[][] = Array.from({ length: n }, () => new Array(n).fill(0));
  for (let i = 0; i < n; i++) G[i][i] = 1;
  for (const a of angles) {
    const value = a.m !== undefined ? -Math.cos(Math.PI / a.m) : -a.cosAlpha;
    G[a.i][a.j] = value;
    G[a.j][a.i] = value;
  }
  return G;
}

/** Symmetric eigenvalues via the Jacobi eigenvalue algorithm -- small fixed matrices (n<=6 here), no external linear-algebra dependency needed. */
export function symmetricEigenvalues(matrix: number[][], iterations = 100): number[] {
  const n = matrix.length;
  const A = matrix.map((row) => [...row]);
  for (let iter = 0; iter < iterations; iter++) {
    let p = 0, q = 1, max = 0;
    for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) if (Math.abs(A[i][j]) > max) { max = Math.abs(A[i][j]); p = i; q = j; }
    if (max < 1e-12) break;
    const theta = A[p][p] === A[q][q] ? Math.PI / 4 : 0.5 * Math.atan2(2 * A[p][q], A[p][p] - A[q][q]);
    const c = Math.cos(theta), s = Math.sin(theta);
    const App = c * c * A[p][p] + s * s * A[q][q] + 2 * s * c * A[p][q];
    const Aqq = s * s * A[p][p] + c * c * A[q][q] - 2 * s * c * A[p][q];
    for (let k = 0; k < n; k++) {
      if (k === p || k === q) continue;
      const Akp = A[k][p], Akq = A[k][q];
      A[k][p] = A[p][k] = c * Akp + s * Akq;
      A[k][q] = A[q][k] = -s * Akp + c * Akq;
    }
    A[p][p] = App; A[q][q] = Aqq; A[p][q] = A[q][p] = 0;
  }
  return A.map((row, i) => row[i]).sort((a, b) => a - b);
}
