/**
 * Source text of krp-core's polyhedra/stellations/pieces.generated.js (shared by the generator and the
 * verify script's staleness check).
 */
import { POLYHEDRA, CATALAN_ADDITION_IDS } from '../krp-core/src/polyhedra/index.js';
import { type Vec3, centerVertices, facesCongruent, triangulateFace } from '../krp-core/src/polyhedra/core.js';
import { STELLATION_SIZES, stellationPieceOnFace } from '../krp-core/src/polyhedra/stellations/build.js';

/**
 * The solids that get stellation pieces, Platonic first: every face-
 * transitive convex solid with an insphere in the registry (the
 * tetrahedron, octahedron and icosahedron live in Deltahedra as D4, D8
 * and D20).
 */
export const STELLATED_SOLIDS = ['D4', 'CUBE', 'D8', 'DODECAHEDRON', 'D20', ...CATALAN_ADDITION_IDS];

export interface GeneratedPiece {
  solid: string;
  size: number;
  hand?: 'left' | 'right';
  vertices: Vec3[];
  faces: number[][];
  baseFace: number;
}

/**
 * Faces of a scalene-faced Catalan come in two mirror-image kinds, which
 * no rotation of the solid swaps, so each size has a left and a right
 * piece. A face is "right" when, going round it anticlockwise seen from
 * outside, its sides grow from shortest to longest.
 */
function handOf(vertices: Vec3[], face: number[]): 'left' | 'right' {
  const len = face.map((v, i) => Math.hypot(...(vertices[face[(i + 1) % face.length]].map((x, j) => x - vertices[v][j]) as Vec3)));
  const shortest = len.indexOf(Math.min(...len));
  return len[(shortest + 1) % len.length] < len[(shortest + 2) % len.length] ? 'right' : 'left';
}

export function volume(vertices: Vec3[], faces: number[][]): number {
  let v = 0;
  for (const f of faces) for (const [a, b, c] of triangulateFace(f, vertices)) {
    const [p, q, r] = [vertices[a], vertices[b], vertices[c]];
    v += (p[0] * (q[1] * r[2] - q[2] * r[1]) + p[1] * (q[2] * r[0] - q[0] * r[2]) + p[2] * (q[0] * r[1] - q[1] * r[0])) / 6;
  }
  return v;
}

/**
 * The sizes a solid really has: size 1 (flat) always; a stellation only
 * if it exists (the tetrahedron and cube have none, the octahedron one)
 * and adds something to the one before.
 */
export function generateStellations(): Record<string, GeneratedPiece> {
  const out: Record<string, GeneratedPiece> = {};
  for (const solid of STELLATED_SOLIDS) {
    const spec = POLYHEDRA[solid];
    const vertices = centerVertices(spec.vertices);
    const face0 = spec.faces[0];
    const sides = new Set(face0.map((v, i) => Math.hypot(...(vertices[face0[(i + 1) % face0.length]].map((x, j) => x - vertices[v][j]) as Vec3)).toFixed(6)));
    const scalene = face0.length === 3 && sides.size === 3;
    // One face of each kind: face 0, and for scalene faces its mirror image.
    const faces: { index: number; hand?: 'left' | 'right' }[] = [{ index: 0 }];
    if (scalene) {
      const mirror = spec.faces.findIndex((f) => facesCongruent(vertices, face0, vertices, f));
      faces[0].hand = handOf(vertices, face0);
      faces.push({ index: mirror, hand: handOf(vertices, spec.faces[mirror]) });
      if (faces[0].hand === faces[1].hand) throw new Error(`${solid}: mirror face has the same hand`);
    }
    for (const { index, hand } of faces) {
      let previous = 0;
      for (const size of STELLATION_SIZES) {
        let piece;
        try {
          piece = stellationPieceOnFace(vertices, spec.faces, index, size);
        } catch {
          break; // no bounded cells: no stellation of this size
        }
        const v = volume(piece.vertices, piece.faces);
        if (v <= previous + 1e-9) break; // nothing new: the stellations end here
        previous = v;
        const id = `STELLATION_${solid}_${size}${hand ? `_${hand === 'left' ? 'L' : 'R'}` : ''}`;
        out[id] = { solid, size, ...(hand ? { hand } : {}), vertices: centerVertices(piece.vertices), faces: piece.faces, baseFace: piece.baseFace };
      }
    }
  }
  return out;
}

const round = (x: number) => {
  const r = Number(x.toPrecision(15));
  return Object.is(r, -0) ? 0 : r;
};

export function generateStellationSource(): string {
  const pieces = generateStellations();
  const body = Object.entries(pieces)
    .map(([id, p]) => {
      const verts = p.vertices.map((v) => `[${v.map(round).join(', ')}]`).join(', ');
      const faces = p.faces.map((f) => `[${f.join(', ')}]`).join(', ');
      return `  ${id}: { solid: '${p.solid}', size: ${p.size},${p.hand ? ` hand: '${p.hand}',` : ''} baseFace: ${p.baseFace},\n    vertices: [${verts}],\n    faces: [${faces}] },`;
    })
    .join('\n');
  return `// Generated by Polyhedraverse's scripts/generate-stellations.ts -- do not edit by hand.
// verify:stellations fails if this is stale. Its types are in pieces.generated.d.ts.
export const STELLATION_PIECES = {
${body}
};
`;
}
