/**
 * Stage 6 driver/report: closes the group generated by the RD's own 6
 * distinct <110> mirror planes, runs the orbit test on a generic point,
 * and computes the pairwise-angle Gram matrix + its eigenvalues.
 * See reflectionGroup.ts's own file header for why this specific
 * interpretation (the RD's intrinsic point-group mirror system, not an
 * aggregate-specific 4D lift) was chosen, and
 * docs/composite-seed-rcp/reflectionGroup.md for the full writeup.
 */
import {
  distinctRdMirrorNormals,
  rdGeneratingReflections,
  reflectionMatrix3,
  closeGroup,
  orbitOfPoint,
  pairwiseAngles,
  gramMatrix,
  symmetricEigenvalues,
} from '../app/lib/polyhedra/composite-seed-rcp/reflectionGroup';
import { DELTA_RD } from '../app/lib/polyhedra/composite-seed-rcp/lattice';

let failures = 0;
function check(label: string, cond: boolean) {
  console.log(`${cond ? 'ok' : 'FAIL'}: ${label}`);
  if (!cond) failures++;
}

// -----------------------------------------------------------------
// v and -v give the identical reflection matrix -- checked directly.
// -----------------------------------------------------------------
for (const d of DELTA_RD) {
  const n = Math.hypot(d[0], d[1], d[2]);
  const v: [number, number, number] = [d[0] / n, d[1] / n, d[2] / n];
  const negV: [number, number, number] = [-v[0], -v[1], -v[2]];
  const rv = reflectionMatrix3(v);
  const rNegV = reflectionMatrix3(negV);
  const same = rv.every((row, i) => row.every((c, j) => Math.abs(c - rNegV[i][j]) < 1e-9));
  check(`reflectionMatrix3(v) === reflectionMatrix3(-v) for v=[${v.map((c) => c.toFixed(3))}]`, same);
}

const distinctNormals = distinctRdMirrorNormals();
check('DELTA_RD (12 directions) collapses to exactly 6 distinct mirror planes', distinctNormals.length === 6);
console.log('\nDistinct RD mirror normals:', distinctNormals.map((v) => `[${v.map((c) => c.toFixed(3)).join(',')}]`));

// -----------------------------------------------------------------
// Group closure.
// -----------------------------------------------------------------
const generators = rdGeneratingReflections();
const closure = closeGroup(generators, 200);
console.log(`\nGroup closure: order=${closure.order}, closed=${closure.closed}`);
check('Group closure terminated (did NOT hit the 200 safety cap) -- confirms finiteness directly, not assumed', closure.closed);
check('Group order is one of the KNOWN finite point-group orders for a <110>-generated subgroup of O_h (<=48)', closure.order <= 48);

// -----------------------------------------------------------------
// Orbit test on a genuine generic point (irrational-looking, no
// coordinate symmetry of its own).
// -----------------------------------------------------------------
const genericPoint: [number, number, number] = [1.23456789, 2.3456781, -0.87654321];
const orbit = orbitOfPoint(closure.elements, genericPoint);
console.log(`\nOrbit of generic point [${genericPoint}]: size=${orbit.length}`);
check('Orbit size of a genuine generic point equals the group order (trivial stabilizer)', orbit.length === closure.order);

// A LESS generic point (already on one of the mirror planes, e.g. x=y)
// should have a SMALLER orbit (nontrivial stabilizer) -- checked as a
// sanity cross-check that the machinery is behaving as real reflection
// geometry predicts, not just producing a number.
const onMirrorPoint: [number, number, number] = [1, 1, 2.5]; // lies on the x=y mirror plane
const orbit2 = orbitOfPoint(closure.elements, onMirrorPoint);
console.log(`Orbit of a point ON one mirror plane [${onMirrorPoint}]: size=${orbit2.length}`);
check('A point lying on a mirror plane has a SMALLER orbit than the group order (nontrivial stabilizer)', orbit2.length < closure.order);

// -----------------------------------------------------------------
// Pairwise angles, Coxeter compatibility, Gram matrix, eigenvalues.
// -----------------------------------------------------------------
const angles = pairwiseAngles(distinctNormals);
console.log('\nPairwise angles among the 6 distinct mirror normals:');
for (const a of angles) {
  console.log(`  (${a.i},${a.j}): alpha=${a.alphaDeg.toFixed(4)}deg  m=${a.m ?? 'none'}`);
}
const allCoxeterCompatible = angles.every((a) => a.m !== undefined);
check('Every pairwise angle among the 6 mirrors is individually Coxeter-compatible (integer m)', allCoxeterCompatible);

const G = gramMatrix(distinctNormals, angles);
console.log('\nIdealized Gram matrix G_ij = -cos(pi/m_ij) (the 6 generators are REDUNDANT for this group -- see note below):');
for (const row of G) console.log('  ', row.map((v) => v.toFixed(4)).join('  '));
const idealEigenvalues = symmetricEigenvalues(G);
console.log('Idealized Gram matrix eigenvalues:', idealEigenvalues.map((e) => e.toFixed(6)));

// The REAL (measured, not idealized) Gram matrix of the actual R^3
// vectors -- this one is guaranteed positive-semidefinite of rank <=3
// for ANY finite set of real vectors, finite group or not; it is a
// sanity check on the vector data itself, not a finiteness test.
const realG = distinctNormals.map((a) => distinctNormals.map((b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2]));
const realEigenvalues = symmetricEigenvalues(realG);
const realRank = realEigenvalues.filter((e) => Math.abs(e) > 1e-6).length;
console.log('\nREAL (measured) Gram matrix eigenvalues:', realEigenvalues.map((e) => e.toFixed(6)));
check('REAL Gram matrix of the actual R^3 vectors is positive semi-definite (trivially true for any real vectors)', realEigenvalues.every((e) => e > -1e-6));
check('REAL Gram matrix rank is <=3 (the 6 mirror normals cannot be linearly independent in R^3)', realRank <= 3);

// NOTE on the idealized matrix's own negative eigenvalue: this does
// NOT mean the group is infinite -- direct closure above already
// proved order 24, finite, unambiguously. It means 6 is a REDUNDANT
// (non-minimal) generating set for an order-24 group (whose minimal
// Coxeter rank is 3, not 6) -- the classical "Gram matrix positive
// definite <=> finite" theorem assumes a MINIMAL/independent generating
// set, which this deliberately is not (it's the RD's own full facet
// set, not a hand-picked minimal generator basis). Applying that
// theorem's positive-DEFINITENESS test to a redundant, linearly-
// dependent-in-R^3 generator set is expected to fail exactly like this
// -- a real, reportable structural fact about the RD's own presentation,
// not a bug and not evidence of infiniteness (which the direct
// computation above already rules out).
console.log(
  '\nNote: the idealized matrix\'s negative eigenvalue reflects that these 6 generators are a REDUNDANT ' +
    '(non-minimal) presentation of an order-24 group -- not evidence of infiniteness, which the direct closure ' +
    'and orbit computations above already rule out unambiguously.',
);

// Identify the specific group by its determinant split: pure-rotation O
// (order 24) has every element det=+1; a mixed group like T_d (order
// 24, tetrahedral symmetry incl. reflections) has exactly half of each.
function det3(m: number[][]): number {
  return (
    m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1]) -
    m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0]) +
    m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0])
  );
}
const dets = closure.elements.map((m) => Math.round(det3(m)));
const detPlus = dets.filter((d) => d === 1).length;
const detMinus = dets.filter((d) => d === -1).length;
console.log(`\nDeterminant split: det=+1 (rotations): ${detPlus}, det=-1 (improper/reflections): ${detMinus}`);
check('Group contains BOTH proper and improper elements (rules out the pure-rotation group O)', detPlus > 0 && detMinus > 0);
check('Determinant split is exactly half/half (12/12) -- consistent with T_d, the full tetrahedral point group', detPlus === 12 && detMinus === 12);

console.log(failures === 0 ? '\nAll Stage 6 checks passed.' : `\n${failures} check(s) FAILED.`);
process.exit(failures === 0 ? 0 : 1);
